"""Initial migration

Revision ID: initial_migration
Revises: 
Create Date: 2025-08-12 09:47:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'initial_migration'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('elections',
        sa.Column('id', sa.String(length=50), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('country', sa.String(length=100), nullable=False),
        sa.Column('start_date', sa.DateTime(), nullable=False),
        sa.Column('end_date', sa.DateTime(), nullable=False),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.Column('type', sa.String(length=50), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('timezone', sa.String(length=50), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_elections_country'), 'elections', ['country'], unique=False)
    op.create_index(op.f('ix_elections_status'), 'elections', ['status'], unique=False)
    op.create_index(op.f('ix_elections_type'), 'elections', ['type'], unique=False)
    
    op.create_table('constituencies',
        sa.Column('id', sa.String(length=50), nullable=False),
        sa.Column('election_id', sa.String(length=50), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('region', sa.String(length=100), nullable=False),
        sa.Column('type', sa.String(length=50), nullable=False),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.Column('registered_voters', sa.Integer(), nullable=False),
        sa.Column('bulletins_issued', sa.Integer(), nullable=False),
        sa.Column('votes_cast', sa.Integer(), nullable=False),
        sa.Column('participation_rate', sa.Float(), nullable=False),
        sa.Column('anomaly_score', sa.Float(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['election_id'], ['elections.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_constituencies_election_id'), 'constituencies', ['election_id'], unique=False)
    op.create_index(op.f('ix_constituencies_region'), 'constituencies', ['region'], unique=False)
    op.create_index(op.f('ix_constituencies_status'), 'constituencies', ['status'], unique=False)
    op.create_index(op.f('ix_constituencies_type'), 'constituencies', ['type'], unique=False)
    
    op.create_table('transactions',
        sa.Column('id', sa.String(length=50), nullable=False),
        sa.Column('election_id', sa.String(length=50), nullable=False),
        sa.Column('constituency_id', sa.String(length=50), nullable=False),
        sa.Column('type', sa.String(length=50), nullable=False),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.Column('source', sa.String(length=100), nullable=False),
        sa.Column('data', sa.JSON(), nullable=False),
        sa.Column('timestamp', sa.DateTime(), nullable=False),
        sa.Column('anomaly_detected', sa.Boolean(), nullable=False),
        sa.Column('anomaly_reason', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['constituency_id'], ['constituencies.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['election_id'], ['elections.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_constituency_id'), 'transactions', ['constituency_id'], unique=False)
    op.create_index(op.f('ix_transactions_election_id'), 'transactions', ['election_id'], unique=False)
    op.create_index(op.f('ix_transactions_source'), 'transactions', ['source'], unique=False)
    op.create_index(op.f('ix_transactions_status'), 'transactions', ['status'], unique=False)
    op.create_index(op.f('ix_transactions_timestamp'), 'transactions', ['timestamp'], unique=False)
    op.create_index(op.f('ix_transactions_type'), 'transactions', ['type'], unique=False)
    
    op.create_table('alerts',
        sa.Column('id', sa.String(length=50), nullable=False),
        sa.Column('election_id', sa.String(length=50), nullable=False),
        sa.Column('constituency_id', sa.String(length=50), nullable=False),
        sa.Column('type', sa.String(length=50), nullable=False),
        sa.Column('severity', sa.String(length=50), nullable=False),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.Column('message', sa.Text(), nullable=False),
        sa.Column('timestamp', sa.DateTime(), nullable=False),
        sa.Column('data', sa.JSON(), nullable=True),
        sa.Column('comments', sa.JSON(), nullable=True),
        sa.Column('resolution_notes', sa.Text(), nullable=True),
        sa.Column('resolved_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['constituency_id'], ['constituencies.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['election_id'], ['elections.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_constituency_id'), 'alerts', ['constituency_id'], unique=False)
    op.create_index(op.f('ix_alerts_election_id'), 'alerts', ['election_id'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_index(op.f('ix_alerts_timestamp'), 'alerts', ['timestamp'], unique=False)
    op.create_index(op.f('ix_alerts_type'), 'alerts', ['type'], unique=False)
    
    op.create_table('hourly_stats',
        sa.Column('id', sa.String(length=50), nullable=False),
        sa.Column('election_id', sa.String(length=50), nullable=False),
        sa.Column('constituency_id', sa.String(length=50), nullable=False),
        sa.Column('hour', sa.Integer(), nullable=False),
        sa.Column('timestamp', sa.DateTime(), nullable=False),
        sa.Column('transaction_count', sa.Integer(), nullable=False),
        sa.Column('votes_count', sa.Integer(), nullable=False),
        sa.Column('bulletins_issued', sa.Integer(), nullable=False),
        sa.Column('participation_rate', sa.Float(), nullable=False),
        sa.Column('anomaly_count', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['constituency_id'], ['constituencies.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['election_id'], ['elections.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hourly_stats_constituency_id'), 'hourly_stats', ['constituency_id'], unique=False)
    op.create_index(op.f('ix_hourly_stats_election_id'), 'hourly_stats', ['election_id'], unique=False)
    op.create_index(op.f('ix_hourly_stats_hour'), 'hourly_stats', ['hour'], unique=False)
    op.create_index(op.f('ix_hourly_stats_timestamp'), 'hourly_stats', ['timestamp'], unique=False)
    
    op.create_table('file_processing_jobs',
        sa.Column('id', sa.String(length=50), nullable=False),
        sa.Column('election_id', sa.String(length=50), nullable=False),
        sa.Column('file_name', sa.String(length=255), nullable=False),
        sa.Column('file_type', sa.String(length=50), nullable=False),
        sa.Column('file_size', sa.Integer(), nullable=False),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.Column('progress', sa.Float(), nullable=False),
        sa.Column('progress_message', sa.Text(), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('result', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('started_at', sa.DateTime(), nullable=True),
        sa.Column('completed_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['election_id'], ['elections.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_processing_jobs_election_id'), 'file_processing_jobs', ['election_id'], unique=False)
    op.create_index(op.f('ix_file_processing_jobs_file_type'), 'file_processing_jobs', ['file_type'], unique=False)
    op.create_index(op.f('ix_file_processing_jobs_status'), 'file_processing_jobs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_processing_jobs_status'), table_name='file_processing_jobs')
    op.drop_index(op.f('ix_file_processing_jobs_file_type'), table_name='file_processing_jobs')
    op.drop_index(op.f('ix_file_processing_jobs_election_id'), table_name='file_processing_jobs')
    op.drop_table('file_processing_jobs')
    
    op.drop_index(op.f('ix_hourly_stats_timestamp'), table_name='hourly_stats')
    op.drop_index(op.f('ix_hourly_stats_hour'), table_name='hourly_stats')
    op.drop_index(op.f('ix_hourly_stats_election_id'), table_name='hourly_stats')
    op.drop_index(op.f('ix_hourly_stats_constituency_id'), table_name='hourly_stats')
    op.drop_table('hourly_stats')
    
    op.drop_index(op.f('ix_alerts_type'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_timestamp'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_election_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_constituency_id'), table_name='alerts')
    op.drop_table('alerts')
    
    op.drop_index(op.f('ix_transactions_type'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_timestamp'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_status'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_source'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_election_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_constituency_id'), table_name='transactions')
    op.drop_table('transactions')
    
    op.drop_index(op.f('ix_constituencies_type'), table_name='constituencies')
    op.drop_index(op.f('ix_constituencies_status'), table_name='constituencies')
    op.drop_index(op.f('ix_constituencies_region'), table_name='constituencies')
    op.drop_index(op.f('ix_constituencies_election_id'), table_name='constituencies')
    op.drop_table('constituencies')
    
    op.drop_index(op.f('ix_elections_type'), table_name='elections')
    op.drop_index(op.f('ix_elections_status'), table_name='elections')
    op.drop_index(op.f('ix_elections_country'), table_name='elections')
    op.drop_table('elections')
    # ### end Alembic commands ###